trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Instalar PHP 7.4 manualmente
- script: |
    sudo apt-get update
    sudo apt-get install php7.4
    php -v
  displayName: 'Instalar PHP 7.4'


# Instalar e configurar MySQL
- script: |
    sudo apt-get update
    sudo apt-get install mysql-server
    sudo service mysql start
    mysql -e "CREATE DATABASE petshop_db;" -u root
  displayName: 'Instalar e configurar MySQL'

# Executar testes (se aplicável)
- script: |
    ./vendor/bin/phpunit tests
  displayName: 'Rodar testes do PHP com PHPUnit'
  
# Rodar o servidor PHP para verificação
- script: |
    php -S localhost:8000 -t public
  displayName: 'Iniciar servidor PHP local'
